# Generated by Django 5.2 on 2025-05-05 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0003_alter_member_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='JwtRefreshToken',
            fields=[
                ('jwt_refresh_token_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('member_id', models.BigIntegerField()),
                ('refresh_token', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'jwt_refresh_token',
            },
        ),
    ]
